var searchData=
[
  ['dati_20business_20logic_20layer_0',['3.3 Gestione dei Dati (Business Logic Layer)',['../md_Design_2Documentazione.html#autotoc_md7',1,'']]],
  ['decomposizione_20e_20modularità_1',['6.1 Decomposizione e Modularità',['../md_Design_2Documentazione.html#autotoc_md22',1,'']]],
  ['dei_20componenti_2',['3. Analisi dei Componenti',['../md_Design_2Documentazione.html#autotoc_md4',1,'']]],
  ['dei_20dati_20business_20logic_20layer_3',['3.3 Gestione dei Dati (Business Logic Layer)',['../md_Design_2Documentazione.html#autotoc_md7',1,'']]],
  ['dei_20requisiti_20scadenza_201_20dicembre_4',['2. Ingegneria dei requisiti (Scadenza 1 Dicembre)',['../md_README.html#autotoc_md29',1,'']]],
  ['del_20progetto_2016_2019_20dicembre_5',['5. Discussione e presentazione del Progetto (16 - 19 Dicembre)',['../md_README.html#autotoc_md34',1,'']]],
  ['del_20sistema_6',['1. Panoramica del Sistema',['../md_Design_2Documentazione.html#autotoc_md1',1,'']]],
  ['dell_20accoppiamento_20coupling_7',['6.3 Analisi dell&apos;Accoppiamento (Coupling)',['../md_Design_2Documentazione.html#autotoc_md24',1,'']]],
  ['dell_20interfaccia_20ui_20logic_8',['3.2 Controller dell&apos;Interfaccia (UI Logic)',['../md_Design_2Documentazione.html#autotoc_md6',1,'']]],
  ['della_20coesione_20cohesion_9',['6.2 Analisi della Coesione (Cohesion)',['../md_Design_2Documentazione.html#autotoc_md23',1,'']]],
  ['delle_20eccezioni_10',['3.6 Gestione delle Eccezioni',['../md_Design_2Documentazione.html#autotoc_md10',1,'']]],
  ['delle_20scelte_20progettuali_20e_20analisi_20qualitativa_11',['6. Giustificazione delle Scelte Progettuali e Analisi Qualitativa',['../md_Design_2Documentazione.html#autotoc_md21',1,'']]],
  ['delle_20specifiche_12',['ANALISI DELLE SPECIFICHE',['../md_Specifiche_2AnalisiDelleSpecifiche.html',1,'']]],
  ['design_13',['3.1 Design',['../md_README.html#autotoc_md31',1,'']]],
  ['design_20by_20contract_14',['6.4 Robustezza e &quot;Design by Contract&quot;',['../md_Design_2Documentazione.html#autotoc_md25',1,'']]],
  ['design_20design_20di_20dettaglio_20scadenza_208_20dicembre_15',['3. Design &amp; Design di dettaglio (Scadenza 8 Dicembre)',['../md_README.html#autotoc_md30',1,'']]],
  ['design_20di_20dettaglo_16',['3.2 Design di dettaglo',['../md_README.html#autotoc_md32',1,'']]],
  ['design_20pattern_20rilevati_17',['4. Design Pattern Rilevati',['../md_Design_2Documentazione.html#autotoc_md12',1,'']]],
  ['dettaglio_20scadenza_208_20dicembre_18',['3. Design &amp; Design di dettaglio (Scadenza 8 Dicembre)',['../md_README.html#autotoc_md30',1,'']]],
  ['dettaglo_19',['3.2 Design di dettaglo',['../md_README.html#autotoc_md32',1,'']]],
  ['di_20dettaglio_20scadenza_208_20dicembre_20',['3. Design &amp; Design di dettaglio (Scadenza 8 Dicembre)',['../md_README.html#autotoc_md30',1,'']]],
  ['di_20dettaglo_21',['3.2 Design di dettaglo',['../md_README.html#autotoc_md32',1,'']]],
  ['di_20dominio_20entities_22',['3.4 Modello di Dominio (Entities)',['../md_Design_2Documentazione.html#autotoc_md8',1,'']]],
  ['di_20gestione_20biblioteca_23',['Documentazione Tecnica: Sistema di Gestione Biblioteca',['../md_Design_2Documentazione.html',1,'']]],
  ['diagrams_24',['5. Vista Dinamica e Flussi Operativi (Sequence Diagrams)',['../md_Design_2Documentazione.html#autotoc_md14',1,'']]],
  ['dicembre_25',['dicembre',['../md_README.html#autotoc_md29',1,'2. Ingegneria dei requisiti (Scadenza 1 Dicembre)'],['../md_README.html#autotoc_md30',1,'3. Design &amp; Design di dettaglio (Scadenza 8 Dicembre)'],['../md_README.html#autotoc_md33',1,'4. Implementazione e testing (Scadenza 15 Dicembre)'],['../md_README.html#autotoc_md34',1,'5. Discussione e presentazione del Progetto (16 - 19 Dicembre)']]],
  ['dinamica_20e_20flussi_20operativi_20sequence_20diagrams_26',['5. Vista Dinamica e Flussi Operativi (Sequence Diagrams)',['../md_Design_2Documentazione.html#autotoc_md14',1,'']]],
  ['disattiva_27',['disattiva',['../classsoftwareeng_1_1biblioteca_1_1model_1_1Prestito.html#a018823652e5097ed29712edde52605fc',1,'softwareeng.biblioteca.model.Prestito.disattiva()'],['../interfacesoftwareeng_1_1biblioteca_1_1model_1_1GestionePrestiti.html#ade5296f095a54f6a05e569e8b7736279',1,'softwareeng.biblioteca.model.GestionePrestiti.disattiva()'],['../classsoftwareeng_1_1biblioteca_1_1controller_1_1PrestitiController.html#ab5f0d1c23638bd55f8dae316935d129e',1,'softwareeng.biblioteca.controller.PrestitiController.disattiva()']]],
  ['discussione_20e_20presentazione_20del_20progetto_2016_2019_20dicembre_28',['5. Discussione e presentazione del Progetto (16 - 19 Dicembre)',['../md_README.html#autotoc_md34',1,'']]],
  ['documentazione_20tecnica_3a_20sistema_20di_20gestione_20biblioteca_29',['Documentazione Tecnica: Sistema di Gestione Biblioteca',['../md_Design_2Documentazione.html',1,'']]],
  ['dominio_20entities_30',['3.4 Modello di Dominio (Entities)',['../md_Design_2Documentazione.html#autotoc_md8',1,'']]],
  ['downcopie_31',['downCopie',['../classsoftwareeng_1_1biblioteca_1_1model_1_1Libro.html#af0abe5237920d47a1302d81f01a73730',1,'softwareeng::biblioteca::model::Libro']]],
  ['dry_32',['6.5 Principio DRY',['../md_Design_2Documentazione.html#autotoc_md26',1,'']]]
];
